### ISSUE TITLE
Error running dotdocker on Ubuntu 18.04

### ISSUE THREAD

**Issue by outkaj** [aj-may/dotdocker#24]
**Describe the bug** dotdocker fails with resolution error during configuration on an Ubuntu 18.04 VM

**To Reproduce** 

make sure `docker-proxy` is stopped by running `docker-proxy stop`
`sudo systemctl stop systemd-resolved` (note - if I restart this before running `dotdocker` I get the same error)
add 8.8.8.8 to `/etc/resolv.conf`
`sudo npm install -g dotdocker`
kill any processes on ports 53, 80, 443
`sudo dotdocker start`

output:

```
sudo: unable to resolve host ip-*machine-ip*
  ❯ Start dotdocker containers
    ❯ Start proxy
      ⠏ Pulling codekitchen/dinghy-http-proxy:latest
        → 4c394a654280: Download complete
        Creating dotdocker-proxy
        Starting dotdocker-proxy
    ❯ Start dnsmasq
      ✔ Pulling andyshinn/dnsmasq:latest
      ✔ Creating dotdocker-dnsmasq
      ✖ Starting dotdocker-dnsmasq
        → (HTTP code 500) server error - driver failed programming external connectivity on endpoint dotdocker-dnsmasq (697c21fa66b20918b27c81da376
…
    Setting up DNS
(node:8818) UnhandledPromiseRejectionWarning: Error: (HTTP code 500) server error - driver failed programming external connectivity on endpoint dotdocker-dnsmasq (697c21fa66b20918b27c81da3761a7a38055af0ae7705d0c826afa9c35d883c5): Error starting userland proxy:  
    at /usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:257:17
    at getCause (/usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:232:14)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:8818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8818) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior** I would expect dotdocker setup to succeed. 

**Screenshots** N/A (see log output above)

**Additional context** aj-may mentioned making sure no other process was running on port 53 and making sure Docker has permissions to listen on that port. I've checked the first but not the second - would the best way to do the latter just be to run `sudo /usr/bin/docker daemon -H tcp://0.0.0.0:53 -H unix:///var/run/docker.sock`?

**Comment by outkaj** [comment]
I've gotten past that error and on to a later one: 

```
✖ Starting dotdocker-dnsmasq
        → (HTTP code 500) server error - driver failed programming external connectivity on endpoint dotdocker-dnsmasq (7dae2c6db5e4deb199b0e24df6e
…
    Setting up DNS
(node:20519) UnhandledPromiseRejectionWarning: Error: (HTTP code 500) server error - driver failed programming external connectivity on endpoint dotdocker-dnsmasq (7dae2c6db5e4deb199b0e24df6eee7b131bc88ce0eb644cb74d4d411b630f3a5): Error starting userland proxy:  
    at /usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:257:17
    at getCause (/usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:232:14)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:20519) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20519) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
