### ISSUE TITLE
failed to create new OS thread (have 2 already; errno=22)

### ISSUE THREAD

**Issue by anilpeechara** [aj-may/dotdocker#41]
**Describe the bug** A clear and concise description of what the bug is.
Seeing dinghy-http-proxy container failing with below on mac pro with M1 chip. Keeps on retrying but ends with the same error.

WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
is being generated in the background. Once the new dhparam.pem is in place, nginx will be reloaded.
Generating DH parameters, 2048 bit long safe prime, generator 2
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x884500, 0x9)
/usr/local/go1.6/src/runtime/panic.go:530 +0x90
runtime.newosproc(0xc820026000, 0xc820035fc0)
/usr/local/go1.6/src/runtime/os1_linux.go:149 +0x18c
runtime.newm(0x932358, 0x0)
/usr/local/go1.6/src/runtime/proc.go:1513 +0x135
runtime.main.func1()
/usr/local/go1.6/src/runtime/proc.go:125 +0x2c
runtime.systemstack(0xa8e800)
/usr/local/go1.6/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
/usr/local/go1.6/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
/usr/local/go1.6/src/runtime/asm_amd64.s:245 fp=0xc820020770 sp=0xc820020768
runtime.main()
/usr/local/go1.6/src/runtime/proc.go:126 +0x62 fp=0xc8200207c0 sp=0xc820020770
runtime.goexit()
/usr/local/go1.6/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200207c8 sp=0xc8200207c0
runtime: failed to create new OS thread (have 2 already; errno=22)

**To Reproduce** Steps to reproduce the behavior:
Try starting on Apple Macbook Pro with M1 chip

dotdocker start 

**Expected behavior** A clear and concise description of what you expected to happen.

**Screenshots** If applicable, add screenshots to help explain your problem.
<img width="1051" alt="Screen Shot 2021-04-30 at 3 01 52 PM" src="https://user-images.githubusercontent.com/133066/116742215-10c61300-a9c5-11eb-804b-4a8ce00d41db.png">

**Additional context** Add any other context about the problem here.

**Comment by aj-may** [comment]
@anilpeechara thank you for reporting this bug.  I have determined that one of the docker images this project relies on does not work on M1 chips.  It also appears that image is not being actively maintained.  We are currently working on a fix
